### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by danpaz** [nanek/ladderapp#5]
I hit a few snags getting this up and running from scratch:
- `watch` looks for dist/bundle.js which doesn't yet exist.
- `build` creates js/bundle.min.js. Should this instead build dist/bundle.js?
- Port 8282 is in use on my machine, mysteriously. Maybe it's [itunes](https://www.adminsub.net/tcp-udp-port-finder/8282)??
- This error output on `npm run build`:

```
> ladder@1.0.0 build /Users/danielpazsoldan/devs/ladderapp
> browserify . -t [envify --NODE_ENV production] | uglifyjs -cm > js/bundle.min.js

Parse error at -:211,9
Unexpected token punc «,», expected punc «:»
Error
```

I think this is just a typo on line 211 of the bundle.

**Comment by danpaz** [comment]
@nanek I have a branch to fix these ^. Can you give push permission so I can make a PR? Alternatively I can do the ol' fork & PR.

**Comment by nanek** [comment]
Added as collaborator. Thanks!

**Comment by nanek** [comment]
`watch` is failing as the folder dist does not exist. It was originally using the folder js.

**Comment by nanek** [comment]
Fixed.
